name: mock_server
description: A template for building mock servers.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_hotreload: ^1.0.1
  shelf_router: ^1.0.0
  shelf_router_generator: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.7
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
